CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

IMU_LEFT_TOKEN_INDEX = -300
IMU_RIGHT_TOKEN_INDEX = -400
AUDIO_TOKEN_INDEX = -500
DEFAULT_IMU_LEFT_TOKEN="<imu_left>"
DEFAULT_IMU_RIGHT_TOKEN="<imu_right>"
DEFAULT_AUDIO_TOKEN="<audio>"
